services:
 
  backend_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_service
    ports:
      - "3000:3000"
    volumes:
      - ./:/src
      - backend_node_modules:/src/node_modules
    networks:
      - nest_network
    restart: always
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    command: npm run start:dev


networks:
  nest_network:
    driver: bridge

volumes:
  backend_node_modules:
    driver: local



